# Disable the newline at the start of the prompt
add_newline = true

# Replace the "â¯" symbol in the prompt with "âœ"
[character]      # The name of the module we are configuring is "character"
success_symbol  = "ğŸ§‰"
error_symbol = "ğŸ§‰"

[git_branch]
symbol = "ğŸŒ³ "

[aws]
disabled = true
