[homebrew.files."homebrew/base.Brewfile"]
target = "~/Brewfile"
type= "template"
append = """

{{ include_template "homebrew/metabase.Brewfile" }}
"""

[zsh.files."zsh/zshrc/.zshrc"]
target = "~/.zshrc"
type= "template"
append = """

{{ include_template "zsh/zshrc/metabase.zshrc" }}
"""

[zsh.files."zsh/config-metabase"]
target = "~/.config/zsh"

[zsh.files."zsh/.zshenv"]
target = "~/.zshenv"
type= "template"
append = """

{{ include_template "zsh/zshenv/metabase.zshenv" }}
"""

[zsh.files."zsh/config-metabase"]
target = "~/.config/zsh"
